### ISSUE TITLE
Please provide a README

### ISSUE THREAD

**Issue by PHHargrove** [StanfordLegion/gasnet#1]
This repo contains fairly old tarballs of GASNet.  
For somebody who searched GitHub for repos named "gasnet", this could be confusing.  
Could you please add a top-level README.txt or README.md clarifying the role and/or nature of this repository? 
We'd appreciate something that directs folks looking for GASNet to http://gasnet.lbl.gov if that is not too much to ask.

Thanks,
-Paul

cc: bonachea

**Comment by streichler** [comment]
A totally reasonable request.  I'll try to take care of this today.

**Comment by elliottslaughter** [comment]
I added an initial README, which should now appear on the main page for the repo: https://github.com/StanfordLegion/gasnet

If we can do anything to further improve our communication around this repo, please let us know.

**Comment by PHHargrove** [comment]
Thank you, @elliottslaughter.  
This should help avoid the confusion I was concerned about.
