### ISSUE TITLE
Quartz: `No supported spawner was able to initialize the job`

### ISSUE THREAD

**Issue by cmelone** [StanfordLegion/gasnet#18]
The [Quartz](https://hpc.llnl.gov/hardware/compute-platforms/quartz) system recently updated to a new OS (TOSS4). When executing our solver, I encounter this error:

```
[melone1@quartz380:tol]$ cat slurm-114005.out
Sending output to out
Invoking Legion on 2 rank(s), 2 node(s) (1 rank(s) per node), as follows:
/usr/WS1/stanf_ci/psaap-ci/artifacts/1163525/HTR-solver/src/prometeo_ConstPropMix.exec -o out -i 4x1x1.json -ll:cpu 1 -ll:ocpu 2 -ll:onuma 1 -ll:othr 35 -ll:ostack 8 -ll:util 2 -ll:io 1 -ll:bgwork 2 -ll:cpu_bgwork 100 -ll:util_bgwork 100 -ll:csize 100000 -lg:eager_alloc_percentage 30 -ll:rsize 512 -ll:ib_rsize 512 -ll:gsize 0 -ll:stacksize 8 -lg:sched -1 -lg:hysteresis 0
*** FATAL ERROR (quartz3:1855953): in gasneti_spawnerInit() at lease/language/gasnet/GASNet-2022.9.2/gasnet_internal.c:2424: No supported spawner was able to initialize the job
*** WARNING (quartz3:1855953): Ignoring call to gasneti_print_backtrace_ifenabled before gasneti_backtrace_init
srun: error: quartz3: task 0: Aborted (core dumped)
*** FATAL ERROR (quartz4:635441): in gasneti_spawnerInit() at lease/language/gasnet/GASNet-2022.9.2/gasnet_internal.c:2424: No supported spawner was able to initialize the job
*** WARNING (quartz4:635441): Ignoring call to gasneti_print_backtrace_ifenabled before gasneti_backtrace_init
srun: error: quartz4: task 1: Aborted (core dumped)
```

We are using the `ofi-omnipath` network config.

This did not occur before the OS update, and our codebase has not changed. Could be that Slurm is screwing up somehow?

**Comment by elliottslaughter** [comment]
@PHHargrove @bonachea Do we need an explicit `--enable-pmi` or similar on the command line? I think we were expecting it to auto-configure before, but maybe we need to be more explicit.

**Comment by elliottslaughter** [comment]
@cmelone You might attach your `config.log` from your GASNet build here so we can see what spawners GASNet was configured with.

**Comment by PHHargrove** [comment]
GASNet's configure script should auto-detect PMI w/o a configure argument, and the attached `config.log` seems to show PMIx was found under `/usr`.  However, it looks like Open MPI's `mpirun` was _mistakenly_ identified as the spawner command.  When `PMIx_Init()` failed, the reported message was the result.

You probably need a `--with-pmirun-cmd=...` argument (or `PMIRUN_CMD` in the environment).   I don't _know_ what the right value might be for Quartz, but my _guess_ is `srun --mpi=pmix %V -n %N -- %C`.

**Comment by cmelone** [comment]
thanks. Just to clarify, `PMIRUN_CMD` can be set at run-time?

**Comment by PHHargrove** [comment]
Yes, `PMIRUN_CMD` set at run-time will be honored.
Setting it at configure time just established a default.

**Comment by elliottslaughter** [comment]
@cmelone How are you launching your job? I thought you were already doing something like:

```
srun ... ./legion_application ...
```

In which case, shouldn't `PMIRUN_CMD` be irrelevant? The job has already been launched. What we need to do is hint to GASNet to connect to the PMI job that already exists.

**Comment by PHHargrove** [comment]
I agree `PMIRUN_CMD` is not relevant if `srun` is used directly.
If that is that case , then adding `--mpi=pmix` to the `srun` command may be the key.

**Comment by cmelone** [comment]
adding `--mpi=pmix` fixed it! thank you @elliottslaughter @PHHargrove
