### ISSUE TITLE
Segfault on multinode

### ISSUE THREAD

**Issue by thiagotei** [StanfordLegion/gasnet#20]
I have an error when running Legion in multiple nodes at [Pascal@LLNL](https://hpc.llnl.gov/hardware/compute-platforms/pascal).
Using Gasnet version `2022.9.0`, `CONDUIT=ibv`  and modules ` 1) jobutils/1.0   2) StdEnv (S)   3) gcc/11.2.1-magic   4) mvapich2/2.3.6   5) cuda/11.8.0   6) cmake/3.23.1   7) python/3.9.12 `.
Pascal uses Slurm and `srun` to spawn the jobs.
```
$  srun --mpi=list
MPI plugin types are...
        pmi2
        cray_shasta
        none
        pmix
specific pmix plugin versions available: pmix_v3
```

With `srun --mpi=pmix <app>`, there is no error, but it seems that it is running two independent jobs because it prints everything twice.
With `srun --mpi=pmi2 <app>` or just `srun <app>` the result is the following:
```
[pascal41:mpi_rank_1][error_sighandler] Caught error: Segmentation fault (signal 11)
[pascal40:mpi_rank_0][error_sighandler] Caught error: Segmentation fault (signal 11)
srun: error: pascal41: task 1: Segmentation fault (core dumped)
srun: error: pascal40: task 0: Segmentation fault (core dumped)
```

An MPI hello world works fine with `srun --mpi=pmi2` or just `srun`:
```
Hello world from processor pascal40, rank 0 out of 2 processors
Hello world from processor pascal41, rank 1 out of 2 processors
```
MPI hello world with `srun --mpi=pmix` has the following (incorrect) output:
```
Hello world from processor pascal145, rank 0 out of 1 processors
Hello world from processor pascal145, rank 0 out of 1 processors
```

I have built gasnet with `--with-pmi-version=2` to force the use of `pmi2`, but nothing changed.
Appreciate any help in debugging this.

**Comment by bonachea** [comment]
@thiagotei can you share your configure / install commands for GASNet / Legion?

This is probably orthogonal to the spawning problem, but it looks like Pascal has an Omni-Path network; so you should probably be using [config.ofi-omnipath.release](https://github.com/StanfordLegion/gasnet/blob/master/configs/config.ofi-omnipath.release) with ofi-conduit and psm2 provider (assuming that provider is installed) instead of ibv-conduit (the verbs emulation layer on Omni-Path is very slow).  I'd also advise use of the latest GASNet version 2023.3.0, which includes some conduit fixes relevant to Omni-Path.

CC: @PHHargrove

**Comment by thiagotei** [comment]
@bonachea thanks for the guidance!
I am using [setup_env.sh](https://gitlab.com/StanfordLegion/legion/-/blob/control_replication/language/scripts/setup_env.py) to install Legion and Gasnet.
I thought about using `config.ofi-omnipath.release`, but I found information internally at the LLNL systems saying that it uses Infiniband Mellanox.
```
================================ job.lim.pascal ================================
      SUMMARY OF INTERACTIVE AND BATCH JOB LIMITS ON PASCAL
      ------------------------------------------------------------------------
   
      HARDWARE:
      Each compute node has 2 18-core Intel Xeon E5-2695 v4 processors
      @2.1 GHz, 256 GiB of memory and 2 NVIDIA P100 (Pascal) GPUs.
      The login node pascal83 has 128 GiB of memory and no GPUs.
      Hyperthreading is enabled, giving compute nodes 72 cores.
      Pascal uses a Mellanox EDR (100 GB) InfiniBand interconnect.
```
I am going to try `ofi-omnipath` with the 2023.3.0 version.

**Comment by bonachea** [comment]
@thiagotei I don't have access to or experience with Pascal, my comments were entirely based on the page linked in your first comment which includes:

> Interconnect: Cornelis Networks Omni-Path

which argues for `ofi-omnipath`

However further down on the same page I now see:

> Pascal uses a Mellanox EDR (100 GB) InfiniBand interconnect.

which is a very different network hardware that would argue for ibv-conduit.

So you should probably get clarification on the what interconnect hardware is actually installed on the compute nodes. The output of a command like `srun -n 1 lspci` may be helpful.

**Comment by thiagotei** [comment]
It looks like it is infiniband:

```
$ srun -n 1 lspci | grep Infi
08:00.0 Infiniband controller: Mellanox Technologies MT27800 Family [ConnectX-5]
```

**Comment by bonachea** [comment]
Yes it appears you have genuine Mellanox InfiniBand, so ibv-conduit is the preferred choice.

So back to the original problem, the next hurdle is to figure out why job spawning is not working for you.  The output from GASNet configure might be helpful here, as it may have found a non-functional PMI library (does `module avail pmi` show anything useful?). It would also help to know if MPI compatibility is enabled and whether GASNet is using the same MPI install that you successfully tested using your MPI hello world.

It's worth noting that GASNet supports job spawning via any of PMI, MPI or SSH, so selecting a different option might also bring us closer to a solution. However based on the information you've provided so far I'm not even sure which of the first two options is being attempted.

**Comment by thiagotei** [comment]
It is working! I've updated the gasnet to `2023.3.0` with `ibv-conduit`.
Multinode output is good.
Thanks for the help @bonachea

**Comment by bonachea** [comment]
Great to hear @thiagotei !

Did you ever get a diagnosis of the root cause, or did things just inexplicably start working when you upgraded version?

**Comment by thiagotei** [comment]
Updated and it worked. Not sure what is the cause.
