### ISSUE TITLE
Job launch failure

### ISSUE THREAD

**Issue by cmelone** [StanfordLegion/gasnet#25]
I started receiving this error on [Quartz](https://hpc.llnl.gov/hardware/compute-platforms/quartz), which uses the `ofi-omnipath` conduit.

```
srun: error: timeout waiting for task launch, started 0 of 1 tasks
srun: StepId=2166087.0 aborted before step completely launched.
```

The job is launched with `srun --mpi=pmix`, and fails with both 2023.3.0 and 2023.9.0. I was able to get a minimal reproducer using the Legion "hello world" program. I reached out to the support to see if anything changed around the date we noticed the issue. In the meantime, I was wondering if you had any tips for debugging? Thanks

[config.log](https://github.com/StanfordLegion/gasnet/files/14135518/config.log)

**Comment by elliottslaughter** [comment]
@PHHargrove @bonachea I'm wondering if you can provide some debugging suggestions for this issue.

@cmelone was able to get this to a minimal reproducer: we're running a hello world Legion C++ program at this point. This should be about as simple as it gets.

My only thought is that maybe GASNet is not configured to use the correct PMI, somehow, but I don't know what to check there.

Thanks.

**Comment by PHHargrove** [comment]
@elliottslaughter and @cmelone 

While I am not familiar with that specific message from srun, it sounds like at least the GASNet initialization code isn't running and maybe not even main().  I have three suggested steps toward debugging this:

Try again with `--mpi=X` for X set to each of the options given in the output of `srun --mpi=list`.
In particular, there may be `pmix_v3` or `pmix_4` options that are distinct from `pmix`.

Next, I suggest reducing the problem even further to `srun  --mpi=pmix ... echo hello`, with the "..." including any other settings used originally, to check that srun can launch even trivial jobs.

Assuming the "echo" test works, my second suggestion is to compile a simple MPI-based hello world and check if it can run correctly.  You may again need to try multiple `--mpi=X` options to get something that works.

Of course if you've already run MPI hello world successfully, then you can ignore the latter two ideas (as they won't provide new information).

**Comment by cmelone** [comment]
```
MPI plugin types are...
	pmix
	cray_shasta
	pmi2
	none
specific pmix plugin versions available: pmix_v3
```

Running with `pmix_v3` gets me the same error, while specifying the other plugins results in `Requested spawner "ssh" failed to initialize`.

`srun -p pdebug --mpi=pmix ... echo hello` also gets me the original error. Just curious, what is the importance of the ellipses?

The support folks are wondering why I specify `pmix` rather than the default `pmi2`. I don't know enough about the details of GASNet/Legion to give them a great answer, but I know that we originally established that I should use `--mpi=pmix` in https://github.com/StanfordLegion/gasnet/issues/18.

**Comment by PHHargrove** [comment]
@cmelone 

The message about `Requested spawner "ssh"` _might_ be due to a fall back to ssh following failure of the PMI initialization handshake due to the wrong argument to `--mpi=`.  If you can rerun with `GASNET_IBV_SPAWNER=pmi` in the environment, then GASNet will only attempt PMI-based job launch.  Though I still expect failures, I feel the tests are worth trying for completeness.

The ellipses was meant as a placeholder for any options you'd used originally but had not specified in this issue.
Please try without the "...".   Sorry for any confusion.

I suspect that the support folks set the default `--mpi=pmi2` to correspond to what their Open MPI install uses (I noticed it in the `$PATH` in the provided `config.log`).
However, `--mpi=pmix` is needed because GASNet's configure script located the install of PMIx and has linked to it.

**Comment by cmelone** [comment]
Now getting `Requested spawner "pmi" failed to initialize`.

Either way, a simple `srun -p pdebug --mpi=pmix echo hi` reproduces the issue. I will let them know that we depend on pmix, not pmi2 and see what they say.

thanks for all your help!

**Comment by cmelone** [comment]
this is being investigated as a slurm/pmix issue now https://bugs.schedmd.com/show_bug.cgi?id=18874
